version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/tmp/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=2h'
      - '--web.enable-lifecycle'
      - '--enable-feature=remote-write-receiver'
      - '--web.external-url=https://monitoring.exemple.com/prometheus/'
      - '--web.route-prefix=/'
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks: 
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-@dm!n26}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=monitoring.exemple.com
      - GF_SERVER_ROOT_URL=http://monitoring.exemple.com/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    command: 
      - '-config.file=/etc/loki/local-config.yaml'
      - 'server.path-prefix=/loki'
    volumes:
      - ./loki.yml:/etc/loki/config.yaml
      - loki:/data/loki
    networks:
      - monitoring
  
  web:
    build: .
    container_name: web
    volumes:
      - ./web/db.sqlite:/app/front/db.sqlite
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DO_TOKEN=dop_v1_xxx
      - APP_ADMIN_EMAIL=email@domain.com
      - APP_ADMIN_PASS=changme
      - APP_URL=https://admin.exemple.com
      - MONITORING_URL=https://monitoring.exemple.com

networks:
  monitoring:

volumes:
  grafana:
  loki:
  prometheus:
